# Docker Compose
version: '3'

services:
  db:
    restart: always
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=go_scaffold
    ports:
      - 3306:3306 # host:container

  api:
    build: .
    ports:
      - 5000:5001 # host:container
    environment:
      - ENV=docker-dev
      - PORT=5001
    command: ./wait-for-it.sh -t 60 db:3306 -- go run cmd/api/run.go