databases:
  go_scaffold:
    user: root
    password: ""
    protocol: tcp
    address: localhost:3306
port: 8081
access_token_secret: "super_secret_key" # For JWTs
refresh_token_secret: "super_secret_key" # For JWTs
domain: localhost
cookie_secure: false
